  language:
  - node_js

  node_js: "11.2.0"

  branches:
  only:
  - master

  before_script:
    - npm install -g firebase-tools
    - npm install -g @angular/cli
    - npm install -g firebase @angular/fire

  script:
    - ng build

  after_success:
    - firebase deploy --token $FIREBASE_TOKEN
